name: ci
on: push
jobs:
  get-build-id:
    runs-on: ubuntu-20.04
    steps:
      - name: Print the build id 🖨
        uses: bahmutov/get-build-id@HEAD
        id: get-build-id
        with:
          url: 'https://next-ts-app-swart.vercel.app/'

      - name: Print the outputs 🖨
        run: |
          echo "Next.js build ID: ${{ steps.get-build-id.outputs.buildId }}"
          echo "Next.js build branch: ${{ steps.get-build-id.outputs.branch }}"
          echo "Next.js build commit: ${{ steps.get-build-id.outputs.commit }}"
